workflows:
  ios-build:
    name: iOS Build and Distribution
    instance_type: mac_mini_m1
    max_build_duration: 120 # minutes

    environment:
      vars:
        XCODE_WORKSPACE: 'ios/doan.xcworkspace' # Tên workspace của bạn
        XCODE_SCHEME: 'doan' # Tên scheme của bạn
        BUNDLE_ID: 'org.reactjs.native.example.doan' # Bundle ID của ứng dụng
      node: 18 # Phiên bản Node.js bạn sử dụng
      xcode: 15.3 # Phiên bản Xcode bạn muốn sử dụng

    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Install CocoaPods dependencies
        script: |
          set -e # Exit immediately if a command exits with a non-zero status.
          set -x # Print commands and their arguments as they are executed.
          cd ios
          rm -rf Pods/ Podfile.lock # Clean up previous Pods and lock file
          pod repo update # Update CocoaPods master repo
          pod install --repo-update # Install pods and update repo if needed
          ls -la # List contents of ios directory to confirm .xcworkspace creation

      - name: Set up code signing
        script: |
          # Codemagic sẽ tự động sử dụng provisioning profiles và certificates đã tải lên
          # Không cần lệnh thủ công nếu đã cấu hình trong UI

      - name: Build iOS App
        script: |
          cd ios
          xcodebuild -workspace doan.xcworkspace -scheme $XCODE_SCHEME -configuration Release -sdk iphoneos archive -archivePath build/Runner.xcarchive DEVELOPMENT_TEAM=xnrn8shps4

      - name: Export IPA
        script: |
          cd ios
          xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build

    artifacts:
      - build/ios/*.ipa
      - build/ios/Runner.xcarchive # Tùy chọn: lưu trữ archive để debug sau

    publishing:
      email:
        recipients:
          - nguyendoanh55555@gmail.com
      # Bạn có thể cấu hình các dịch vụ phân phối tại đây (ví dụ: TestFlight, App Store Connect)
      # Xem tài liệu Codemagic để biết thêm: https://docs.codemagic.io/yaml/publishing/ 